- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  canBeAntag: false
  icon: JobIconBorg
  setPreference: true
  supervisors: job-supervisors-ce
  jobEntity: PlayerBorgGeneric
