- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: true # WYPT-14
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  setPreference: false # WYPT-14


- type: startingGear
  id: PrisonGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard #DeltaV
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpsuitPrisonGuard
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
