- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 259200 # DeltaV - 72 hours
  - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          traits:
            - ShadowkinBlackeye
