- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 86400 # DeltaV - 24 hours
  - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          traits:
            - ShadowkinBlackeye